= Hands-on #3. Developing shopping cart.
:experimental:
:icons: font
:idprefix:
:idseparator: -
:imagesdir: step-3
:nbsp:
:sectanchors:
:sectlinks:
:sectnums:
:source-highlighter: prettify
:toc:

== Implementing ShoppingCartService

. Generate new service with following Angular CLI command:
+
[source, shell]
----
$ ng generate service shared/services/shopping-cart --spec false
----

. Re-export `ShoppingCartService` from _src/app/shared/services/index.ts_ file:
+
[source, ts]
----
export * from './shopping-cart.service';
----

. Replace content of the _shopping-cart.service.ts_ file with the following code:
+
[source, ts]
----
import { Injectable } from '@angular/core';

interface ShoppingCartState {
  [key: string]: number;
}

const SHOPPING_CART_KEY = 'ngs_shopping_cart';

@Injectable()
export class ShoppingCartService {

  private state: ShoppingCartState;

  constructor() {
    this.state = this.loadState() || {};
  }

  get totalQuantity(): number {
    return Object.keys(this.state).reduce((total, productId) => {
      return total + this.state[productId];
    }, 0);
  }

  getItems(): ShoppingCartState {
    // Return a copy of the shopping cart's state.
    return Object.assign({}, this.state);
  }

  setItems(items: ShoppingCartState): void {
    this.state = items;
    this.saveState();
  }

  addItem(productId: string, quantity: number): void {
    if (quantity > 0) {
      this.state[productId] = (this.state[productId] || 0) + quantity;
      this.saveState();
    }
  }

  removeItem(productId: string): void {
    delete this.state[productId];
    this.saveState();
  }

  setQuantity(productId: string, quantity: number): void {
    if (quantity > 0) {
      this.state[productId] = quantity;
      this.saveState();
    } else {
      this.removeItem(productId);
    }
  }

  private loadState(): ShoppingCartState {
    return JSON.parse(localStorage.getItem(SHOPPING_CART_KEY));
  }

  private saveState(): void {
    localStorage.setItem(SHOPPING_CART_KEY, JSON.stringify(this.state));
  }
}
----

. Add `ShoppingCartService` to the list of `AppModule` providers in the _src/app/app.module.ts_ file:
+
[source, ts]
----
import { ProductService, ShoppingCartService } from './shared/services'; // <1>

@NgModule({
  // Module declarations, imports go here...
  providers: [ ProductService ], // <1>
  bootstrap: [ AppComponent ]
})
export class AppModule {}
----
<1> Add service to the import statement.
<2> Add `ShoppingCartService` to the list of `AppModule` providers.

. Commit the changes to save the progress:
+
[source, shell]
----
$ git add -A && git commit -m "Add shopping cart service"
----

== Generating and configuring routing for CartComponent



== Implementing CartComponent

== Making add-to-cart button work on product page

== Adding shopping cart icon button to the toolbar


////
TODO:
* Add toast notification on the product page
////
